import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import '@/styles/main.scss'
import { ReactNode } from 'react'

const mainrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={mainrope.className}>{children}</body>
    </html>
  )
}
