import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import '@/styles/main.scss'
import { ReactNode } from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

const mainrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${mainrope.className} mt-[97px]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
